-- Atualizando script para usar os nomes corretos das colunas da tabela orders
-- Script corrigido para inserir pedidos de exemplo com dados completos
-- Remove pedidos existentes vazios e insere novos com informações corretas

-- Limpa pedidos vazios existentes
DELETE FROM orders WHERE name = '' OR name IS NULL;

-- Insere 10 pedidos de exemplo com dados completos
INSERT INTO orders (
  id,
  order_number,
  name,
  telefone,
  address,
  items,
  payment,
  subtotal,
  delivery_fee,
  total,
  status,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  '1001',
  'João Silva',
  '(11) 99999-1234',
  'Rua das Flores, 123 - Centro - São Paulo/SP',
  '[{"id":"1","name":"X-Burger","quantity":2,"price":25.90,"complements":["Bacon","Queijo extra"]},{"id":"2","name":"Batata Frita","quantity":1,"price":12.50,"complements":[]}]'::jsonb,
  'Cartão de Crédito',
  51.80,
  5.00,
  56.80,
  'novo',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  gen_random_uuid(),
  '1002',
  'Maria Santos',
  '(11) 98888-5678',
  NULL,
  '[{"id":"3","name":"Pizza Margherita","quantity":1,"price":35.00,"complements":["Borda recheada"]}]'::jsonb,
  'PIX',
  35.00,
  0.00,
  35.00,
  'preparando',
  CURRENT_TIMESTAMP - INTERVAL '15 minutes',
  CURRENT_TIMESTAMP - INTERVAL '10 minutes'
),
(
  gen_random_uuid(),
  '1003',
  'Pedro Costa',
  '(11) 97777-9012',
  NULL,
  '[{"id":"4","name":"Açaí 500ml","quantity":1,"price":18.00,"complements":["Granola","Banana","Mel"]}]'::jsonb,
  'Dinheiro',
  18.00,
  0.00,
  18.00,
  'pronto',
  CURRENT_TIMESTAMP - INTERVAL '25 minutes',
  CURRENT_TIMESTAMP - INTERVAL '5 minutes'
),
(
  gen_random_uuid(),
  '1004',
  'Ana Oliveira',
  '(11) 96666-3456',
  'Av. Paulista, 456 - Bela Vista - São Paulo/SP',
  '[{"id":"5","name":"Hambúrguer Artesanal","quantity":1,"price":32.00,"complements":["Cheddar","Bacon"]},{"id":"6","name":"Refrigerante 350ml","quantity":2,"price":6.00,"complements":[]}]'::jsonb,
  'Cartão de Débito',
  44.00,
  7.00,
  51.00,
  'em_entrega',
  CURRENT_TIMESTAMP - INTERVAL '45 minutes',
  CURRENT_TIMESTAMP - INTERVAL '20 minutes'
),
(
  gen_random_uuid(),
  '1005',
  'Carlos Ferreira',
  '(11) 95555-7890',
  NULL,
  '[{"id":"7","name":"Pastel de Carne","quantity":3,"price":8.50,"complements":[]},{"id":"8","name":"Caldo de Cana","quantity":1,"price":5.00,"complements":[]}]'::jsonb,
  'Dinheiro',
  30.50,
  0.00,
  30.50,
  'concluido',
  CURRENT_TIMESTAMP - INTERVAL '1 hour',
  CURRENT_TIMESTAMP - INTERVAL '30 minutes'
),
(
  gen_random_uuid(),
  '1006',
  'Lucia Mendes',
  '(11) 94444-2468',
  'Rua Augusta, 789 - Consolação - São Paulo/SP',
  '[{"id":"9","name":"Salada Caesar","quantity":1,"price":28.00,"complements":["Frango grelhado"]},{"id":"10","name":"Suco Natural","quantity":1,"price":8.00,"complements":["Laranja"]}]'::jsonb,
  'PIX',
  36.00,
  6.00,
  42.00,
  'novo',
  CURRENT_TIMESTAMP - INTERVAL '5 minutes',
  CURRENT_TIMESTAMP - INTERVAL '5 minutes'
),
(
  gen_random_uuid(),
  '1007',
  'Roberto Lima',
  '(11) 93333-1357',
  NULL,
  '[{"id":"11","name":"Espetinho de Carne","quantity":5,"price":4.50,"complements":[]},{"id":"12","name":"Farofa","quantity":1,"price":6.00,"complements":[]}]'::jsonb,
  'Cartão de Crédito',
  28.50,
  0.00,
  28.50,
  'preparando',
  CURRENT_TIMESTAMP - INTERVAL '20 minutes',
  CURRENT_TIMESTAMP - INTERVAL '15 minutes'
),
(
  gen_random_uuid(),
  '1008',
  'Fernanda Rocha',
  '(11) 92222-9753',
  'Rua Oscar Freire, 321 - Jardins - São Paulo/SP',
  '[{"id":"13","name":"Sushi Combo","quantity":1,"price":45.00,"complements":["Wasabi","Shoyu"]}]'::jsonb,
  'Cartão de Crédito',
  45.00,
  8.00,
  53.00,
  'novo',
  CURRENT_TIMESTAMP - INTERVAL '2 minutes',
  CURRENT_TIMESTAMP - INTERVAL '2 minutes'
),
(
  gen_random_uuid(),
  '1009',
  'Gustavo Alves',
  '(11) 91111-8642',
  NULL,
  '[{"id":"14","name":"Tapioca","quantity":2,"price":12.00,"complements":["Queijo","Presunto"]},{"id":"15","name":"Café","quantity":1,"price":4.00,"complements":[]}]'::jsonb,
  'Dinheiro',
  28.00,
  0.00,
  28.00,
  'pronto',
  CURRENT_TIMESTAMP - INTERVAL '30 minutes',
  CURRENT_TIMESTAMP - INTERVAL '10 minutes'
),
(
  gen_random_uuid(),
  '1010',
  'Isabela Torres',
  '(11) 90000-7531',
  'Rua da Consolação, 654 - República - São Paulo/SP',
  '[{"id":"16","name":"Lasanha Bolonhesa","quantity":1,"price":38.00,"complements":[]},{"id":"17","name":"Salada Verde","quantity":1,"price":15.00,"complements":["Molho italiano"]}]'::jsonb,
  'PIX',
  53.00,
  7.50,
  60.50,
  'em_entrega',
  CURRENT_TIMESTAMP - INTERVAL '35 minutes',
  CURRENT_TIMESTAMP - INTERVAL '25 minutes'
);
